version: '3.9'

services:
  nginx:
    build: .
    ports:
      - "80:80"
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND=${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    expose:
      - "6379"
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND=${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  default:

volumes:
  postgres_data:
  static_volume:
  redis_data:
