# Generated by Django 5.2.5 on 2025-08-09 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время должно быть не менее 1 секунды"
                    ),
                    django.core.validators.MaxValueValidator(
                        120, message="Время не должно превышать 120 секунд"
                    ),
                ],
                verbose_name="Время на выполнение (в секундах)",
            ),
        ),
    ]
