name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: '3.12'

      - name: Instal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root
          
      - name: Run migrate
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
