name: Django CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ~/.cache/pypoetry
            ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.create true
          poetry install --no-interaction --no-ansi --no-root
          
      - name: Run migrate
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          HOST: localhost
          PORT: 5432
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: poetry run python manage.py migrate

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: poetry run python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          cat << EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_HOST=db
          REDIS_HOST=redis
          CELERY_BROKER_URL=redis://redis:6379
          CELERY_RESULT_BACKEND=redis://redis:6379
          EOF
#
#      - name: Create docker-compose.prod.yml
#        run: |
#          cat << EOF > docker-compose.prod.yml
#          services:
#            web:
#              build:
#                context: .
#                dockerfile: Dockerfile
#              env_file:
#                - .env
#              ports:
#                - "80:8000"
#              volumes:
#                - .:/app
#                - static_volume:/code/static
#              depends_on:
#                db:
#                  condition: service_healthy
#                redis:
#                  condition: service_healthy
#
#            db:
#              image: postgres
#              env_file:
#                - .env
#              ports:
#                - "5432:5432"
#              volumes:
#                - postgres_data:/var/lib/postgresql/data
#              healthcheck:
#                test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d ${POSTGRES_DB}']
#                interval: 30s
#                timeout: 10s
#                retries: 5
#
#            redis:
#              image: redis:alpine
#              ports:
#                - "6379:6379"
#              healthcheck:
#                test: [ 'CMD', 'redis-cli', 'ping' ]
#                interval: 30s
#                timeout: 10s
#                retries: 5
#
#            celery:
#              build:
#                context: .
#                dockerfile: Dockerfile
#              command: celery -A config worker --loglevel=info
#              env_file:
#                - .env
#              volumes:
#                - .:/app
#              depends_on:
#                db:
#                  condition: service_healthy
#                redis:
#                  condition: service_healthy
#
#            celery_beat:
#              build:
#                context: .
#                dockerfile: Dockerfile
#              command: celery -A config beat --loglevel=info
#              env_file:
#                - .env
#              volumes:
#                - .:/app
#              depends_on:
#                db:
#                  condition: service_healthy
#                redis:
#                  condition: service_healthy
#
#          volumes:
#            postgres_data:
#            static_volume:
#            redis_data:
#          EOF

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Server
        run: |
          scp -o StrictHostKeyChecking=no .env docker-compose.prod.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d --name myapp -p 80:8000 --env-file .env ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
#          cd ~
#          sudo apt update
#          sudo apt install docker-compose-plugin
#          sudo docker compose -f docker-compose.prod.yml down
#          sudo docker compose -f docker-compose.prod.yml pull
#          sudo docker compose -f docker-compose.prod.yml up -d
          EOF
